motor_spec:
    gear_ratio : 250
    wheel_base : 0.165   # 0.16 worked  # 0.17
    wheel_radius : 0.03375
    enc_pulse : 44

use_imu_during_odom_calc:
    use_imu : True
    complementary_filter_coef : 0.5
